<!--==========================
  Header
  ============================-->
  <header id="header">

    <div class="container">

      <div class="logo float-left">
        <!-- Uncomment below if you prefer to use an image logo -->
        <h1 class="text-light"><a href="index.php" class="scrollto"><span>QUERCU</span></a></h1>
        <!--<a href="#header" class="scrollto"><img src="img/logo.jfif" alt="" width = "50%" height = "100%" class="img-fluid"></a>-->
      </div>

      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          <li><a href="property.php">Property</a></li>
          <li><a href="owner.php">Owner</a></li>
          <li><a href="propertyType.php">Property Type</a></li>
        </ul>
      </nav><!-- .main-nav -->
      
    </div>
  </header><!-- #header -->